version: 2.1

orbs:
  codecov: codecov/codecov@volatile

executors:
  default:
    docker:
      - image: circleci/golang:1.14-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout

      - run: make check-style

  test_backend:
    executor:
      name: default
    steps:

      - checkout

      - run: go get -v -t -d ./...
      - run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - codecov/upload:
          file: "coverage.txt"
          flags: "backend"
        
  test_frontend:
    executor:
      name: default
    steps:

      - checkout

      - run: cd webapp && npm install
      - run: cd webapp && npm run test

      - codecov/upload:
          file: "coverage.txt"
          flags: "frontend"

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test_backend
      - test_frontend