version: 2.1

orbs:
  codecov: codecov/codecov@volatile

jobs:
  build:
    docker:
      - image: circleci/golang:1.14-node
    working_directory: ~/repo
    steps:

      - checkout

      - run: go get -v -t -d ./...
      - run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - codecov/upload:
          file: "coverage.txt"
